# Generated by Django 6.0 on 2025-12-11 09:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Advertisement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('image_url', models.URLField(max_length=500)),
                ('target_url', models.URLField(max_length=500)),
                ('click_count', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('active_hour_start', models.PositiveSmallIntegerField(help_text='开始小时 (0-23)', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(23)])),
                ('active_hour_end', models.PositiveSmallIntegerField(help_text='结束小时 (0-23)，若小于开始小时则表示跨天', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(23)])),
                ('target_os', models.CharField(choices=[('ios', 'iOS'), ('android', 'Android'), ('windows', 'Windows'), ('all', 'All')], default='all', help_text='广告目标 OS：iOS / Android / Windows / All', max_length=16)),
                ('target_lat', models.FloatField(blank=True, help_text='目标纬度 (WGS84)', null=True)),
                ('target_lon', models.FloatField(blank=True, help_text='目标经度 (WGS84)', null=True)),
                ('radius_meters', models.PositiveIntegerField(blank=True, help_text='有效半径（米）。为空表示不使用地理围栏（作为通用广告）', null=True)),
                ('is_generic', models.BooleanField(default=False, help_text='是否为通用广告（位置失败或无匹配时的兜底广告）')),
                ('weight', models.FloatField(default=0.0, help_text='权重，兜底/通用广告时使用，值越大优先级越高')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'ads_advertisement',
                'ordering': ['-weight', '-created_at'],
            },
        ),
    ]
