# Generated by Django 6.0 on 2025-12-11 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField()),
                ('mac_address', models.CharField(blank=True, help_text='可选：通过 ARP/DHCP 记录的 MAC 地址', max_length=32, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('is_authenticated', models.BooleanField(default=False)),
                ('first_seen', models.DateTimeField(auto_now_add=True)),
                ('last_seen', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'ads_client_session',
                'indexes': [models.Index(fields=['ip_address'], name='ads_client__ip_addr_406701_idx')],
            },
        ),
    ]
