# Generated by Django 6.0 on 2025-12-12 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0002_clientsession'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientsession',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='clientsession',
            name='location_accuracy_m',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='clientsession',
            name='location_updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='clientsession',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='clientsession',
            name='mac_address',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
