# Generated by Django 6.0 on 2025-12-12 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0003_clientsession_latitude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientsession',
            name='dwell_seconds',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='clientsession',
            name='ended_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='clientsession',
            name='venue_id',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='clientsession',
            name='venue_name',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='clientsession',
            name='venue_type',
            field=models.CharField(blank=True, choices=[('SHOP', '商店'), ('FOOD', '餐饮店'), ('HOTEL', '酒店'), ('OTHER', '其他')], max_length=16, null=True),
        ),
    ]
