# Generated by Django 6.0 on 2025-12-12 11:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0004_clientsession_dwell_seconds_clientsession_ended_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clientsession',
            name='dwell_seconds',
        ),
        migrations.RemoveField(
            model_name='clientsession',
            name='ended_at',
        ),
        migrations.RemoveField(
            model_name='clientsession',
            name='venue_id',
        ),
        migrations.RemoveField(
            model_name='clientsession',
            name='venue_name',
        ),
        migrations.RemoveField(
            model_name='clientsession',
            name='venue_type',
        ),
        migrations.AddField(
            model_name='clientsession',
            name='venue_distance_m',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='Venue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(default='OVERPASS', max_length=16)),
                ('external_id', models.CharField(max_length=64)),
                ('name', models.CharField(max_length=128)),
                ('category', models.CharField(choices=[('SHOP', '商店'), ('FOOD', '餐饮店'), ('HOTEL', '酒店'), ('OTHER', '其他')], default='OTHER', max_length=16)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('tags', models.JSONField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'indexes': [models.Index(fields=['category'], name='ads_venue_categor_796118_idx'), models.Index(fields=['is_active'], name='ads_venue_is_acti_e206d4_idx')],
                'constraints': [models.UniqueConstraint(fields=('source', 'external_id'), name='uniq_venue_source_external_id')],
            },
        ),
        migrations.AddField(
            model_name='clientsession',
            name='venue',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='client_sessions', to='ads.venue'),
        ),
        migrations.AddIndex(
            model_name='clientsession',
            index=models.Index(fields=['is_authenticated'], name='ads_client__is_auth_c61575_idx'),
        ),
        migrations.AddIndex(
            model_name='clientsession',
            index=models.Index(fields=['venue'], name='ads_client__venue_i_afdae8_idx'),
        ),
    ]
