# Generated by Django 6.0 on 2025-12-12 12:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0005_remove_clientsession_dwell_seconds_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='VisitSegment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_key', models.CharField(db_index=True, max_length=32)),
                ('source', models.CharField(choices=[('GEO', 'Geolocation'), ('UNK', 'Unknown/No-Location')], default='UNK', max_length=8)),
                ('start_at', models.DateTimeField()),
                ('end_at', models.DateTimeField()),
                ('is_open', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='visit_segments', to='ads.clientsession')),
                ('venue', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='visit_segments', to='ads.venue')),
            ],
        ),
        migrations.CreateModel(
            name='DeviceVisitState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_key', models.CharField(max_length=32, unique=True)),
                ('pending_count', models.IntegerField(default=0)),
                ('last_ping_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('current_venue', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='current_for_devices', to='ads.venue')),
                ('pending_venue', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pending_for_devices', to='ads.venue')),
                ('current_segment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='current_for_devices', to='ads.visitsegment')),
            ],
        ),
        migrations.AddIndex(
            model_name='visitsegment',
            index=models.Index(fields=['device_key', 'is_open'], name='ads_visitse_device__ede766_idx'),
        ),
        migrations.AddIndex(
            model_name='visitsegment',
            index=models.Index(fields=['device_key', 'start_at'], name='ads_visitse_device__1d1bb6_idx'),
        ),
        migrations.AddIndex(
            model_name='visitsegment',
            index=models.Index(fields=['venue', 'start_at'], name='ads_visitse_venue_i_e7bfad_idx'),
        ),
        migrations.AddIndex(
            model_name='devicevisitstate',
            index=models.Index(fields=['device_key'], name='ads_devicev_device__1eff3a_idx'),
        ),
        migrations.AddIndex(
            model_name='devicevisitstate',
            index=models.Index(fields=['last_ping_at'], name='ads_devicev_last_pi_15fd68_idx'),
        ),
    ]
