# Generated by Django 6.0 on 2025-12-12 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0006_visitsegment_devicevisitstate_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='advertisement',
            options={},
        ),
        migrations.AddIndex(
            model_name='advertisement',
            index=models.Index(fields=['is_active'], name='ads_adverti_is_acti_a1a936_idx'),
        ),
        migrations.AddIndex(
            model_name='advertisement',
            index=models.Index(fields=['active_hour_start', 'active_hour_end'], name='ads_adverti_active__ebd42b_idx'),
        ),
        migrations.AddIndex(
            model_name='advertisement',
            index=models.Index(fields=['target_os'], name='ads_adverti_target__ff8d4f_idx'),
        ),
        migrations.AddIndex(
            model_name='advertisement',
            index=models.Index(fields=['is_generic'], name='ads_adverti_is_gene_da869a_idx'),
        ),
        migrations.AddIndex(
            model_name='advertisement',
            index=models.Index(fields=['target_lat', 'target_lon'], name='ads_adverti_target__706e17_idx'),
        ),
        migrations.AddIndex(
            model_name='advertisement',
            index=models.Index(fields=['radius_meters'], name='ads_adverti_radius__f25c8b_idx'),
        ),
        migrations.AddIndex(
            model_name='advertisement',
            index=models.Index(fields=['weight'], name='ads_adverti_weight_fed669_idx'),
        ),
    ]
