# Generated by Django 6.0 on 2026-01-04

import uuid
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("ads", "0007_alter_advertisement_options_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="AdImpression",
            fields=[
                ("id", models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False, serialize=False)),
                ("visitor_id", models.CharField(max_length=64, db_index=True)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.TextField(blank=True, null=True)),
                ("shown_at", models.DateTimeField(auto_now_add=True)),
                ("clicked_at", models.DateTimeField(blank=True, null=True)),
                ("dwell_ms", models.PositiveIntegerField(blank=True, null=True)),
                ("hour", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("os_name", models.CharField(max_length=16, blank=True, null=True)),
                ("advertisement", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="impressions", to="ads.advertisement")),
            ],
            options={
                "indexes": [
                    models.Index(fields=["visitor_id", "shown_at"], name="ads_adimpr_visitor__b3b9f4_idx"),
                    models.Index(fields=["advertisement", "shown_at"], name="ads_adimpr_adverti_1a2c3d_idx"),
                ],
            },
        ),
        migrations.CreateModel(
            name="UserAdStat",
            fields=[
                ("id", models.BigAutoField(primary_key=True, auto_created=True, serialize=False, verbose_name="ID")),
                ("visitor_id", models.CharField(max_length=64, db_index=True)),
                ("impressions", models.PositiveIntegerField(default=0)),
                ("clicks", models.PositiveIntegerField(default=0)),
                ("dwell_sum_ms", models.BigIntegerField(default=0)),
                ("last_impression_at", models.DateTimeField(blank=True, null=True)),
                ("advertisement", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="user_stats", to="ads.advertisement")),
            ],
        ),
        migrations.AddConstraint(
            model_name="useradstat",
            constraint=models.UniqueConstraint(fields=("visitor_id", "advertisement"), name="uniq_user_ad"),
        ),
        migrations.AddIndex(
            model_name="useradstat",
            index=models.Index(fields=["visitor_id", "advertisement"], name="ads_userads_visitor__c4d5e6_idx"),
        ),
    ]
